// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cjluX_-Zo4X3VakT7WsYeNLBvD_FEh4',
    appId: '1:326792165761:web:1b4391aed4eb331df21080',
    messagingSenderId: '326792165761',
    projectId: 'bell-exchange-abda4',
    authDomain: 'bell-exchange-abda4.firebaseapp.com',
    storageBucket: 'bell-exchange-abda4.appspot.com',
    measurementId: 'G-45C30M9YBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCF4LQprTEnvkHz6gdexQ8Z81-52lfGQ',
    appId: '1:326792165761:android:b437ce611c559aa1f21080',
    messagingSenderId: '326792165761',
    projectId: 'bell-exchange-abda4',
    storageBucket: 'bell-exchange-abda4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEMwwF5Z0IXb05rZvM8Ei9tx3uf6XT1ww',
    appId: '1:326792165761:ios:f5859b8379bb7f7df21080',
    messagingSenderId: '326792165761',
    projectId: 'bell-exchange-abda4',
    storageBucket: 'bell-exchange-abda4.appspot.com',
    iosBundleId: 'com.example.bellExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEMwwF5Z0IXb05rZvM8Ei9tx3uf6XT1ww',
    appId: '1:326792165761:ios:eeebe4626d077f59f21080',
    messagingSenderId: '326792165761',
    projectId: 'bell-exchange-abda4',
    storageBucket: 'bell-exchange-abda4.appspot.com',
    iosBundleId: 'com.example.bellExchange.RunnerTests',
  );
}
